### ISSUE TITLE
Uncaught TypeError: t.indexOf is not a function

### ISSUE THREAD

**Issue by darnold** [FaiblUG/setIframeHeight#5]
I'm using 1.3.0 and i'm getting a weird issue where everything works but in my Chrome console i'm getting the error "Uncaught TypeError: t.indexOf is not a function".  In fact when I open the Chrome console on the demo page https://demo.jonasfischer.net/Faibl/setIframeHeight/ I get a similar error referring to line 164 "if (data.indexOf('::')) {". I'm not a javascript guru. any ideas what's going on here?

**Comment by jfmaeck** [comment]
Hi @darnold, thank your for reporting this issue. It should be solved in version 1.3.1 (just pushed)
