### ISSUE TITLE
setIframeHeight:shrinked

### ISSUE THREAD

**Issue by AlguerGalceran** [FaiblUG/setIframeHeight#6]
I installed the lib as explained but never triggers that event, that when the content in the iFrame reduces the iFrame doesn't change his height and keeps the higher height.
I manage to make it work for me changing the following part marked on bold on the file "set-iframe-height-child.js":

  function getDocumentHeight() {
            var D = document;
            var b = $('body');
            var matches = navigator.userAgent.match(/MSIE (\d)/);
            if (matches && parseInt(matches[1], 10) <=10) {
              return Math.max(D.body.scrollHeight, D.documentElement.scrollHeight);
            }
            return Math.min(
              **Math.min**(D.body.offsetHeight, D.documentElement.offsetHeight),
              **Math.min**(
                Math.max(D.body.scrollHeight, D.documentElement.scrollHeight),
                Math.max(D.body.clientHeight, D.documentElement.clientHeight)
              )
            );
          }

Can you tell me what I'm doing wrong? Or actually, is an issue?

Thanks

**Comment by jfmaeck** [comment]
HI @AlguerGalceran, thank you for your input. Could you please tell me which browser you are using? Could you please check, if the problem also exists in our demo at https://rawgit.com/FaiblUG/setIframeHeight/master/demo/index.html (clicking on the colored areas should shrink/expand them and the iframe height should adjust accordingly)?

If the demo ist working, it might be a problem with the styling within your iframe - if a page is told to take up the entire available space then it effectively cannot shrink.

**Comment by AlguerGalceran** [comment]
Hi @jfmaeck I'm using chrome, but your example works perfectly for me. I will check my CSS but on my test the iFrame size keeps as HMTL size, but body height is lower that and the HTML and doesn't shrink to the body height.

Thanks

**Comment by AlguerGalceran** [comment]
Hi, @jfmaeck I found why wasn't working, I didn't see that HTML was inheriting min-height from another CSS. Now is working perfectly. Thank you much.

**Comment by jfmaeck** [comment]
Hi @AlguerGalceran, no problem. I'm glad it's working now!
